# Generated by Django 5.1.1 on 2025-02-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suimei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meishiki',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
