# Generated by Django 5.1.1 on 2025-02-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suimei', '0002_meishiki_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meishiki',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
