# Generated by Django 5.1.1 on 2025-03-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suimei', '0003_alter_meishiki_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
