# Generated by Django 5.1.1 on 2025-10-10 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suimei', '0004_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meishiki',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Bunseki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('meishiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunsekis', to='suimei.meishiki')),
            ],
        ),
    ]
