# Generated by Django 5.1.1 on 2025-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suimei', '0005_alter_meishiki_description_bunseki'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunseki',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
